lecture3 - added some components, refactored some files
MahimkO/LearnJS-Course pull request #4
Opened 2023-11-22 10:09 UTC by MahimkO

2023-11-23 12:07 UTC, SArchieEdu requested changes

2023-11-23 12:07 UTC, SArchieEdu commented on src/pages/Restaurants-page/Restaurants-page.jsx
> +  }, [activeTab]);
тут переборщил с логикой, на лекции покажу как проще

2023-11-24 08:46 UTC, MahimkO commented on src/pages/Restaurants-page/Restaurants-page.jsx
> +  }, [activeTab]);
refactored

2023-11-27 11:45 UTC, SArchieEdu approved these changes

2023-11-28 17:14 UTC, merged