Lecture 4/hw
MahimkO/LearnJS-Course pull request #5
Opened 2023-11-24 11:09 UTC by MahimkO

2023-11-27 12:00 UTC, SArchieEdu requested changes

2023-11-27 12:00 UTC, SArchieEdu commented on src/components/ReviewForm/ReviewForm.jsx
> +            defaultValue={1}
а как в стейте формы узнать о значении каунтера?

2023-11-30 08:38 UTC, MahimkO commented on src/components/ReviewForm/ReviewForm.jsx
> +            defaultValue={1}
вынес состояние каунтера в useReducer'ы

2023-11-30 14:00 UTC, ArchieSA approved these changes

2023-11-30 17:54 UTC, merged